// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: proto/greet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetServicesClient is the client API for GreetServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetServicesClient interface {
	SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error)
	SayHelloServerStreaming(ctx context.Context, in *NameList, opts ...grpc.CallOption) (GreetServices_SayHelloServerStreamingClient, error)
	SayHelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetServices_SayHelloClientStreamingClient, error)
	SayHelloBidirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetServices_SayHelloBidirectionalStreamingClient, error)
}

type greetServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetServicesClient(cc grpc.ClientConnInterface) GreetServicesClient {
	return &greetServicesClient{cc}
}

func (c *greetServicesClient) SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/greet_service.GreetServices/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServicesClient) SayHelloServerStreaming(ctx context.Context, in *NameList, opts ...grpc.CallOption) (GreetServices_SayHelloServerStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetServices_ServiceDesc.Streams[0], "/greet_service.GreetServices/SayHelloServerStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServicesSayHelloServerStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetServices_SayHelloServerStreamingClient interface {
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetServicesSayHelloServerStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServicesSayHelloServerStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServicesClient) SayHelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetServices_SayHelloClientStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetServices_ServiceDesc.Streams[1], "/greet_service.GreetServices/SayHelloClientStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServicesSayHelloClientStreamingClient{stream}
	return x, nil
}

type GreetServices_SayHelloClientStreamingClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*MessagesList, error)
	grpc.ClientStream
}

type greetServicesSayHelloClientStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServicesSayHelloClientStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServicesSayHelloClientStreamingClient) CloseAndRecv() (*MessagesList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MessagesList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServicesClient) SayHelloBidirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetServices_SayHelloBidirectionalStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetServices_ServiceDesc.Streams[2], "/greet_service.GreetServices/SayHelloBidirectionalStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServicesSayHelloBidirectionalStreamingClient{stream}
	return x, nil
}

type GreetServices_SayHelloBidirectionalStreamingClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetServicesSayHelloBidirectionalStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServicesSayHelloBidirectionalStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServicesSayHelloBidirectionalStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServicesServer is the server API for GreetServices service.
// All implementations must embed UnimplementedGreetServicesServer
// for forward compatibility
type GreetServicesServer interface {
	SayHello(context.Context, *NoParam) (*HelloResponse, error)
	SayHelloServerStreaming(*NameList, GreetServices_SayHelloServerStreamingServer) error
	SayHelloClientStreaming(GreetServices_SayHelloClientStreamingServer) error
	SayHelloBidirectionalStreaming(GreetServices_SayHelloBidirectionalStreamingServer) error
	mustEmbedUnimplementedGreetServicesServer()
}

// UnimplementedGreetServicesServer must be embedded to have forward compatible implementations.
type UnimplementedGreetServicesServer struct {
}

func (UnimplementedGreetServicesServer) SayHello(context.Context, *NoParam) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetServicesServer) SayHelloServerStreaming(*NameList, GreetServices_SayHelloServerStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloServerStreaming not implemented")
}
func (UnimplementedGreetServicesServer) SayHelloClientStreaming(GreetServices_SayHelloClientStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloClientStreaming not implemented")
}
func (UnimplementedGreetServicesServer) SayHelloBidirectionalStreaming(GreetServices_SayHelloBidirectionalStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloBidirectionalStreaming not implemented")
}
func (UnimplementedGreetServicesServer) mustEmbedUnimplementedGreetServicesServer() {}

// UnsafeGreetServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetServicesServer will
// result in compilation errors.
type UnsafeGreetServicesServer interface {
	mustEmbedUnimplementedGreetServicesServer()
}

func RegisterGreetServicesServer(s grpc.ServiceRegistrar, srv GreetServicesServer) {
	s.RegisterService(&GreetServices_ServiceDesc, srv)
}

func _GreetServices_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServicesServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet_service.GreetServices/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServicesServer).SayHello(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetServices_SayHelloServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NameList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServicesServer).SayHelloServerStreaming(m, &greetServicesSayHelloServerStreamingServer{stream})
}

type GreetServices_SayHelloServerStreamingServer interface {
	Send(*HelloResponse) error
	grpc.ServerStream
}

type greetServicesSayHelloServerStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServicesSayHelloServerStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetServices_SayHelloClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServicesServer).SayHelloClientStreaming(&greetServicesSayHelloClientStreamingServer{stream})
}

type GreetServices_SayHelloClientStreamingServer interface {
	SendAndClose(*MessagesList) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetServicesSayHelloClientStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServicesSayHelloClientStreamingServer) SendAndClose(m *MessagesList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServicesSayHelloClientStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetServices_SayHelloBidirectionalStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServicesServer).SayHelloBidirectionalStreaming(&greetServicesSayHelloBidirectionalStreamingServer{stream})
}

type GreetServices_SayHelloBidirectionalStreamingServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetServicesSayHelloBidirectionalStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServicesSayHelloBidirectionalStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServicesSayHelloBidirectionalStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServices_ServiceDesc is the grpc.ServiceDesc for GreetServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet_service.GreetServices",
	HandlerType: (*GreetServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetServices_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHelloServerStreaming",
			Handler:       _GreetServices_SayHelloServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHelloClientStreaming",
			Handler:       _GreetServices_SayHelloClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHelloBidirectionalStreaming",
			Handler:       _GreetServices_SayHelloBidirectionalStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/greet.proto",
}
